<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
	<CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
  </PropertyGroup>
	<ItemGroup>
		<PackageVersion Include="JoinRpg.Common.WebInfrastructure" Version="2026.8.12" />
		<PackageVersion Include="JoinRpg.Common.WebComponents" Version="2026.8.12" />
		<PackageVersion Include="JoinRpg.Common.PrimitiveTypes" Version="2026.8.12" />
		<PackageVersion Include="JoinRpg.Common.EntityFrameworkCore" Version="2026.8.12" />
		<PackageVersion Include="OpenIddict.Client.AspNetCore" Version="7.7.0" />
		<PackageVersion Include="OpenIddict.Client.SystemNetHttp" Version="7.6.1" />
		<PackageVersion Include="OpenIddict.EntityFrameworkCore" Version="7.6.1" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.20" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11" />
		<PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
		<PackageVersion Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
		<PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
		<PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" />
		<PackageVersion Include="morelinq" Version="4.4.0" />
	</ItemGroup>
</Project>