name: Deploy to prod automatically after build
on:
  workflow_run:
    workflows: [Build and publish]
    types: [completed]
    branches: [master]
  workflow_dispatch:

concurrency:
  group: prod
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    permissions: read-all
    uses: ./.github/workflows/deploy-common.yml
    with:
      deployVersion: latest
      environment: twilight
      environment_url: https://twilight.tsarevs.ru
    secrets: inherit
